joints: {
    shoulder_pan_joint: {id: 1, max_angle: 135, min_angle: -135, max_speed: 90},
    shoulder_lift_joint: {id: 2, max_angle: 135, min_angle: -135, max_speed: 90},
    elbow_joint: {id: 3, max_angle: 135, min_angle: -135, max_speed: 90},
    wrist_1_joint: {id: 4, max_angle: 135, min_angle: -135, max_speed: 90},
    wrist_2_joint: {id: 5, max_angle: 135, min_angle: -135, max_speed: 90},
    left_knuckle_joint: {id: 6, max_angle: 135, min_angle: -135, max_speed: 90},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint], action_name: arm_controller/follow_joint_trajectory, onboard: False }
}
